# -*- mode: ruby -*-
# vi: set ft=ruby :
# edited by lee

VAGRANTFILE_API_VERSION = "2"

k8s_cluster = {
  "node1.example.com" => { :ip => "192.168.50.51", :cpus => 1, :memory => 2048 },
  "node2.example.com" => { :ip => "192.168.50.52", :cpus => 1, :memory => 2048 },
	"master.example.com" => { :ip => "192.168.50.50", :cpus => 2, :memory => 4096 },
}
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  k8s_cluster.each do |hostname, info|

    config.vm.define hostname do |cfg|
      cfg.vm.provider "virtualbox" do |vb,override|
        config.vm.box = "centos/7"
        override.vm.network "private_network", ip: "#{info[:ip]}"
        override.vm.host_name = hostname
        vb.name = hostname
				vb.gui = true
        vb.customize ["modifyvm", :id, "--memory", info[:memory], "--cpus", info[:cpus]]
				if "#{hostname}" == "master.example.com" then
					override.vm.provision "shell", path: "ssh_conf.sh", privileged: true
					override.vm.provision "shell", path: "k8s_cluster_install.sh", privileged: true
					override.vm.provision "shell", path: "run_in_master.sh", privileged: true
					override.vm.provision "shell", path: "account.sh", privileged: false
					override.vm.provision "shell", path: "send_pub_key.sh", privileged: false
				else
					override.vm.provision "shell", path: "ssh_conf.sh", privileged: true
					override.vm.provision "shell", path: "k8s_cluster_install.sh", privileged: true
				end  # if end
      end  # provider end
    end  # define end
  end  # each end
end # configure end

